### ISSUE TITLE
ROI centers

### ISSUE THREAD

**Issue by Rneuro** [porteralab/EZcalcium#6] opened 2021-03-09 00:39 UTC
Hello I am using Matlab 2020b - the ROI detection step appears to complete ok, but when I then open the newly generated file in the ROI refinement app, the ROIs shown in pink are the same that were identified in the ROI detection step, but the ROIs shown in black that I can step through in the ROI refinement app do not line up with these pink circles. It seems that the ROI center information is not correct saved in the file at the end of the ROI detection step is incorrect.

**ROI detection final fig:**
![ROIdetection-fig](https://user-images.githubusercontent.com/80295926/110400505-57d6fe00-803d-11eb-8b83-4aa0fa866a3a.jpg)

**ROI refinement - black dot does not line up with a pink circle:**
![ROIrefinement](https://user-images.githubusercontent.com/80295926/110400523-5e657580-803d-11eb-8b19-94eeb28ac503.jpg)

**Comment by bodayw** [comment] 2021-07-06 16:26
Hi,

Thanks for reporting this.

The cause of the bug is that on high-DPI systems (DPI scaling higher than 100% on Windows, or any Mac computers that has a "retina display"), functions like `getframe` in this case, returns a bigger data array than the "logical" size of the UI axes in pixels, thus the coordinates of the black ROI contour calculated before are off by exactly the DPI scaling factor.

Now fixed with 45563db and in release v2.1.2.

**Closed as completed** 2021-07-26 02:13 UTC
