### ISSUE TITLE
Error when running any EzCalcium function

### ISSUE THREAD

**Issue by SianG93** [porteralab/EZcalcium#24] opened 2023-03-06 00:20 UTC
Hi, anytime I add .tif or .avi files to run ROI detection or any other function I receive the error Unable to perform assignment because the size of the left side is 1216-by-1920 and the size of the right side is 1216-by-1920-by-3. Could someone please help me fix this? Thanks

**Comment by bodayw** [comment] 2023-04-03 09:59
Seems like a duplicate of #7

**Closed as completed by bodayw** 2023-04-03 09:59 UTC
