### ISSUE TITLE
Issue exporting data

### ISSUE THREAD

**Issue by jg3558** [porteralab/EZcalcium#12] opened 2022-05-02 23:53 UTC
Hello,

I'm having some issues exporting my data as a .mat file after completing the ROI Refinement. I run through all the ROI and once I click 'export data' the system crashes and the entire Matlab app closes out. This is true for all my files, even on files that I have exported in the past. 

I've tried restarting everything (computer and program), uninstalling and installing again as well as using the newest version of MATLAB 2022a. Still no luck. Other Matlab features seem to work fine so now I'm assuming it is an EZCalcium issue.

I'd appreciate any help. Thanks!

**Comment by bodayw** [comment] 2022-05-06 09:40
Cannot reproduce on my side. I'm on MATLAB 2020b, Windows 10 2004.

> the system crashes and the entire Matlab app closes out

Just to make sure, by this you mean MATLAB closes, not just the EZcalcium "app", right?

> even on files that I have exported in the past.

Do you mean that you could export data in ROI Refinement with an older version of EZcalcium, or what?

**Comment by bodayw** [comment] 2022-06-22 14:02
Closing this. Feel free to re-open if you have updates.

**Closed as completed by bodayw** 2022-06-22 14:02 UTC
