### ISSUE TITLE
Error message when click the "motion correction" 

### ISSUE THREAD

**Issue by YoungwooNoh** [porteralab/EZcalcium#5] opened 2021-02-23 03:40 UTC
Hi

I got EZcalcium GUI but when I click the "motion correction" I got an error message as follow

Function 'getRunningApp' is not defined to 'ez_motion_correction' type ...

error: ez_motion_correction (line 666)
            runningApp = getRunningApp(app);

error: ezcalcium/MotionCorrectionButtonPushed (line 23)
            ez_motion_correction

error using:
matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 335)

Thanks and I will wait for your help

**Comment by bodayw** [comment] 2021-02-23 04:04
Hi,

Upgrade MATLAB to 2020b (or later) should fix this issue.

Duplicate of #3

**Comment by yojetsharma** [comment] 2021-02-23 10:37
Hi,
I am using matlab2020a and still experiencing this issue. Can you help?

**Comment by YoungwooNoh** [comment] 2021-02-23 15:13
I solved the problem with your kind help.
Thanks!

p.s. to yojetsharma, 2020b might be working well

**Comment by bodayw** [comment] 2021-02-26 04:46
Yes, it has to be 2020b.

**Closed as completed by bodayw** 2021-02-26 04:46 UTC
