### ISSUE TITLE
Issue with importing the file

### ISSUE THREAD

**Issue by Lifei7** [porteralab/EZcalcium#13] opened 2022-06-09 19:38 UTC
Hi I run into an issue when I import my file for the motion correction. It says 

"Unable to perform assignment because the size of the left side is 480-by-720 and the
size of the right side is 480-by-720-by-3.

Error in read_file (line 63)
            imData(:,:,i-sframe+1) = Y1;

Error in ez_motion_correction/RunMotionCorrectionButtonPushed (line 240)
                FOV = size(read_file(filename, 1, 1));

Error in matlab.apps.AppBase>@(source,event)executeCallback(appdesigner.internal.service.AppManagementService.instance(),app,callback,requiresEventData,event) (line 63)
            newCallback = @(source, event)executeCallback(appdesigner.internal.service.AppManagementService.instance(), ...
 
Error while evaluating Button PrivateButtonPushedFcn."

My original file is a MOV file with frame width of 720 and frame hight of 450. What should I do to make the file compatible with the program?

**Comment by bodayw** [comment] 2022-06-22 14:04
Duplicate of #7.

Closing.

**Closed as completed by bodayw** 2022-06-22 14:04 UTC
